// Nihar R. Sahoo

// Jan 14, 2014
// This macro to read the ntuple
// generated by the Ahmed pp2009
//_________________________________


#include "TNtuple.h"
Bool_t Check_hot_Tower(Int_t);
Bool_t Check_hot_EtaStrip(Int_t);

void GammaJet_analysis()
{

  //  TFile* f1=new TFile("pp2009/pp2009_12.root");

  

TFile *myFile = new TFile("GammaJet_analysis_Ntuple_9GeV_withRunId.root","recreate");

 mGammajet=new TNtuple("Gammajet","Gammajet","runId:ptTPC:EneT0:TSP:dphif:eh:etav1:z");
 
  char files_name[50];
  char n;
  for(int i=1; i<10;i++)
    {
        n=sprintf (files_name, "/data/smgroup/sm1/nsahoo/GammaJet/pp200R9/pp2009_nihar/pp2009_%d.root",i);
        printf ("%s \n",files_name);

      
      TFile* f1=new TFile(files_name);


  //_____Event QA_______
      Float_t didT, didE, didP, z;
      Float_t EneT0, etav1, phiv1;
      Float_t ptTPC, dEdx, Ppo, Fp, EtaTr;
      Float_t MPos, MNeg;
      Float_t adc11;
      Float_t dphif;
      Float_t TSP, eh, eT, eneT0;
      Float_t etav1, THeta;
      Float_t runId;
  
  // Get Ntuple
  

  TNtuple *CA=(TNtuple*)f1->Get("CA");
  TNtuple *QAA=(TNtuple*)f1->Get("QAA");
  TNtuple *AngleTA=(TNtuple*)f1->Get("AngleTA");

  TNtuple *Track=(TNtuple*)f1->Get("Track");
  TNtuple *Pho=(TNtuple*)f1->Get("Pho");
  TNtuple *New7A=(TNtuple*)f1->Get("New7A");
  TNtuple *New8A=(TNtuple*)f1->Get("New8A");
  TNtuple *FiveLL=(TNtuple*)f1->Get("FiveLL");


  // Get Leaf
  

  TLeaf *l_didT=QAA->GetLeaf("didT");TLeaf *l_EneT0=QAA->GetLeaf("EneT0");

  TLeaf *l_MPos=QAA->GetLeaf("MPos");  TLeaf *l_etav1=QAA->GetLeaf("etav1");
  TLeaf *l_MNeg=QAA->GetLeaf("MNeg");  TLeaf *l_z=QAA->GetLeaf("z");
  TLeaf *l_phiv1=QAA->GetLeaf("phiv1"); TLeaf *l_eneT0=QAA->GetLeaf("eneT0");
   
  TLeaf *l_runId=AngleTA->GetLeaf("runId");

  TLeaf *l_didE=CA->GetLeaf("didE"); 
  TLeaf *l_didP=CA->GetLeaf("didP");
  
  TLeaf *l_ptTPC=Track->GetLeaf("ptTPC");
  TLeaf *l_dEdx=Track->GetLeaf("dEdx");
  TLeaf *l_Fp=Track->GetLeaf("Fp");
  TLeaf *l_EtaTr=Track->GetLeaf("EtaTr");

  TLeaf *l_dphif=Pho->GetLeaf("dphif");  TLeaf *l_THeta=Pho->GetLeaf("THeta");

  TLeaf *l_TSP=New7A->GetLeaf("TSP");
  TLeaf *l_eh=New7A->GetLeaf("eh");

  TLeaf *l_Ppo=New8A->GetLeaf("Ppo");

  TLeaf *l_adc11 = CA->GetLeaf("adc11");
  TLeaf *l_eT = CA->GetLeaf("eT");

  l_didT->SetAddress(&didT);  l_didP->SetAddress(&didP);  l_didE->SetAddress(&didE); l_EneT0->SetAddress(&EneT0);
  l_etav1->SetAddress(&etav1); l_z->SetAddress(&z);
  l_MPos->SetAddress(&MPos);  l_MNeg->SetAddress(&MNeg);
   
  l_runId->SetAddress(&runId); 

  l_phiv1->SetAddress(&phiv1); 

  l_ptTPC->SetAddress(&ptTPC); 
  l_dphif->SetAddress(&dphif); 
  l_TSP->SetAddress(&TSP); 
  l_eh->SetAddress(&eh); 

  l_adc11->SetAddress(&adc11); 
  l_eT->SetAddress(&eT); 
  l_etav1->SetAddress(&etav1); 
  l_dEdx->SetAddress(&dEdx); 
  l_Ppo->SetAddress(&Ppo); 
  l_Fp->SetAddress(&Fp); 
  l_EtaTr->SetAddress(&EtaTr); 
  l_THeta->SetAddress(&THeta); 
  l_eneT0->SetAddress(&eneT0); 

 


  Int_t nentries=(Int_t)QAA->GetEntries();
  //  cout<<nentries<<endl;
  Int_t ncount=0;
  for(Int_t evnt=0; evnt<nentries; evnt++)
    {
     
      QAA->GetEntry(evnt); 
      AngleTA->GetEntry(evnt); 
      CA->GetEntry(evnt); Track->GetEntry(evnt); Pho->GetEntry(evnt);
      New7A->GetEntry(evnt);       FiveLL->GetEntry(evnt); 
      New8A->GetEntry(evnt);

      ncount++;
      if(ncount%500==0)cout<<ncount<<endl;
      //      if(ncount==10000)break;
      //      if (!(runId==10145070)) continue;
      float XE(0); XE=EneT0*sin(2*atan(exp(-1*etav1)));
      if(XE<9. || XE>30.) continue;
      if(adc11 >= 6005) continue;
      if(fabs(eT)>=0.9)continue;
      if(fabs(etav1)>=1)continue;
      if(dEdx == 0)continue;
      if( (Fp/Ppo) <= 0.52) continue;
      if(Fp<15) continue;
      //cout<<Fp<<"  "<<Ppo<<"  "<<(Fp/Ppo)<<endl;
      if(fabs(EtaTr)>=1)continue;
      if (EneT0<6) continue;
      //  if(eneT0*sin(THeta) <= 6)continue;
      //      if(!(EneT0*sin(2*atan(exp(-1*etav1)))>=9.&&EneT0*sin(2*atan(exp(-1*etav1)))<30.)) continue;

      //      cout<<eneT0*sin(THeta)<<endl;
      //      cout<<EtaTr<<endl;
      //	cout<<dEdx<<endl;
      //      cout<<etav1<<endl;
      //      cout<<eT<<endl;

      //      if(adc11 > 2004)cout<<adc11<<endl;

      //       cout<<didT<<"  "<<didP<<"  "<<didE<<"  "<<MPos<<"  "<<MNeg<<endl;
      Bool_t flag_Tower = Check_hot_Tower(didT+1);
      if((flag_Tower))continue;

      Bool_t flag_EtaStrp =  Check_hot_EtaStrip(didE+1);
      if((flag_EtaStrp))continue;

      if((MPos+MNeg) <= 0)continue;
      if(ptTPC > 30. || ptTPC < 1.2)continue;
      //      if(EneT0*sin(2*atan(exp(-1*etav1))) <= 8)continue;

      //       cout<<ptTPC<<"  "<<EneT0<<"  "<<dphif<<"  "<<TSP<<"  "<<eh<<"  "<<etav1<<endl;
      
      
      mGammajet->Fill(runId,ptTPC,EneT0,TSP,dphif,eh,etav1,z);
      
     

    }


  }


  myFile->cd();
 
  mGammajet->Write();
  
 
  myFile->Close();

  
}// end of function Do_plots_gamma_jet




Bool_t Check_hot_Tower(Int_t TwrId)
{

  Int_t T_Id = TwrId;
  
  Int_t x_Id = 0;
  
  
  Int_t hotTower[146]={2,51,142,147,176,188,225,324,342,425,447,485,486,592,638,651,654,675,791,815,900,902,954,955,964,982,1022,1026,1027,1029,1046,1047,1064,1129,1133,1142,1164,1172,1199,1243,1245,1247,1250,1265,1270,1272,1273,1295,1304,1320,1322,1379,1383,1389,1406,1423,1428,1441,1575,1576,1706,1742,1763,1767,1774,1882,1908,1982,1986,2006,2026,2067,2071,2081,2106,2161,2165,2184,2193,2202,2206,2254,2262,2291,2302,2304,2307,2384,2392,2395,2410,2505,2522,2524,2584,2590,2591,2682,2843,2930,3107,3168,3254,3261,3680,3691,3710,3719,3728,3747,3770,3841,3949,3985,4014,4020,4042,4044,4048,4051,4054,4058,4066,4080,4122,4125,4168,4172,4327,4442,4443,4445,4446,4450,4462,4466,4468,4474,4507,4544,4565,4570,4608,4633,4640,4793};
  

   

 for(int i=0; i<146;i++)
   {
     {if(T_Id == hotTower[i]) //cout<<hotTower[i]<<endl;
	 { x_Id = 1;break;}}
   }

  if(x_Id == 1) 
   return kTRUE;
 else return kFALSE;
}


Bool_t Check_hot_EtaStrip(Int_t EtaStpId)
{

  Int_t T_Id = EtaStpId;
  
  Int_t x_Id = 0;
  
  
  Int_t hotTower[320]={407,408,409,410,411,412,415,416,417,418,419,439,441,443,747,749,1143,1165,1167,1183,1185,1789,1790,1791,1792,1793,1794,2057,2058,2059,2060,2061,2062,2066,2075,2847,2848,2849,2850,2851,2965,2966,2967,2968,2969,2970,3132,3134,3136,3142,3144,3422,3423,3424,3425,3426,3427,3428,3598,3687,4271,4272,4273,4274,4275,4276,4277,4325,4327,4745,4759,4761,4765,4767,4769,4773,4775,4947,4948,4949,4950,5005,5006,5007,5008,5009,5010,5011,5073,5074,5075,5076,5077,5090,5359,5361,5699,5822,5823,5824,5825,5826,5827,5828,5847,5848,5849,5850,5990,5992,5994,6275,6363,6364,6365,6366,6367,6368,6369,6701,6890,6891,6892,6893,6894,7332,7334,7342,7444,7447,7481,7499,7625,7631,7633,7641,7668,7669,7792,7949,7950,8075,8077,8083,8085,8089,8093,8310,8693,8699,8960,9087,9089,9094,9267,9269,9273,9275,9281,9440,9441,9443,9447,9448,9449,9450,9451,9592,9598,9739,9741,9743,9889,9891,10024,10040,10042,10043,10189,10191,10193,10199,10201,10348,10349,10350,10773,10775,10777,10781,10783,10785,10797,10798,10799,10800,10801,10910,10948,10949,11099,11305,11306,11307,11308,11309,11310,11389,11391,11393,11397,11398,11399,11400,11401,11645,11691,11693,11699,11839,11841,12440,12442,12444,12448,12450,12565,12567,12569,12583,12589,12591,12597,12598,12599,12600,12601,12707,12708,12709,12710,12711,12712,12725,12733,12739,12740,12741,12742,12743,12744,12747,12748,12749,13039,13040,13041,13043,13048,13049,13167,13173,13175,13341,13347,13349,13489,13490,13491,13492,13493,13495,13886,13887,13888,13889,13890,13891,13940,13946,13947,13948,13949,13950,13951,14224,14230,14236,14248,14250,14380,14381,14382,14383,14384,14385,14386,14525,14533,14539,14541,14547,14548,14549,14550,14689,14691,14693,14847,14849,14850,16294,16489,16491,16631,16633,16639,17085,17091,17982};
  

   

 for(int i=0; i<320;i++)
   {
     {if(T_Id == hotTower[i]) //cout<<hotTower[i]<<endl;
	 { x_Id = 1;break;}}
   }

  if(x_Id == 1) 
   return kTRUE;
 else return kFALSE;
}


